All-Purpose Tool (+3) [1]
Armor, +2 [2]
Shield, +3 [3, 4]
Weapon, +3 [5]
Amulet of the Planes [6]
Absorbing Tattoo [7, 8]
Animated Shield [9]
Arcane Grimoire (+2) [10]
Armor of Invulnerability (Very Rare variant) [11, 12]
Armor of Resistance (Very Rare variant) [13]
Arrow of Slaying [14]
Belt of Fire Giant Strength [15, 16]
Belt of Frost Giant Strength [17]
Belt of Stone Giant Strength [18]
Belt of Hill Giant Strength (Very Rare variant) [19, 20]
Blackrazor (Very Rare variant if applicable) [21]
Bloodwell Vial (+2) [22]
Cloak of Arachnida [23, 24]
Cloak of Invisibility (Very Rare variant) [25]
Cloak of the Bat (Very Rare variant) [26]
Crystal Ball (Very Rare variant) [27, 28]
Dagger of Venom (Very Rare variant) [29]
Defender (Very Rare variant if applicable) [30]
Dragon Scale Mail [31, 32]
Dragon Slayer (Very Rare variant) [33]
Dwarven Plate [34]
Dwarven Thrower (Very Rare variant) [35, 36]
Efreeti Bottle [37]
Flame Tongue (Very Rare variant) [38]
Frost Brand (Very Rare variant) [39, 40]
Gem of Seeing [41]
Giant Slayer [42]
Wings of Flying (Very Rare variant) [43, 44]
Hammer of Thunderbolts [45]
Holy Avenger (Very Rare variant) [46]
Horn of Valhalla (Bronze or Iron) [47, 48]
Instrument of the Bards (Canaith Mandolin, Cli Lyre) [49]
Ioun Stone (Various Very Rare variants) [50]
Luck Blade (Very Rare variant with no wishes) [51, 52]
Mirror of Life Trapping [53]
Nine Lives Stealer (Very Rare variant) [54]
Oathbow (Very Rare variant) [55, 56]
Ring of Regeneration [57]
Ring of Shooting Stars [58]
Ring of Spell Turning [59, 60]
Ring of Telekinesis [61]
Robe of Eyes [62]
Rod of Absorption [63, 64]
Rod of Alertness [65]
Rod of Security [66]
Rod of the Pact Keeper (+3) [67, 68]
Manual of Bodily Health [69]
Manual of Gainful Exercise [70]
Manual of Quickness of Action [71, 72]
Tome of Clear Thought [73]
Tome of Leadership and Influence [74]
Tome of Understanding [75, 76]
Spellguard Shield [77]
Wand of the War Mage, +3 [78]
Wand of Polymorph [79, 80]
Staff of Fire [81]
Staff of Frost [82]
Staff of Power [83, 84]
Staff of Striking [85]
Staff of Thunder and Lightning [86]
Staff of Withering (Very Rare variant) [87, 88]
Sun Blade (Very Rare variant) [89]
Sword of Answering (Very Rare variant) [90]
Sword of Life Stealing (Very Rare variant) [91, 92]
Sword of Sharpness [93]
Sword of Wounding (Very Rare variant) [94]
Scimitar of Speed (Very Rare variant) [95, 96]
Dancing Sword [97]
Vorpal Sword [98]
Well of Many Worlds [99, 100]